### ISSUE TITLE
Any Plans to support custom grid sizes?

### ISSUE THREAD

**Issue by SanduRajapakse** [1forh/bs-grid-chrome-extension#3]
I am currently working on an application that uses a custom grid size (greater than 12) and would love it if it would overlay accordingly.

**Comment by caesarbell** [comment]
@SanduRajapakse I am in the same situation right as well, and I would love to be able to use this extension regardless of the grid column size.

**Comment by 1forh** [comment]
I will look into this sometime this week! Thanks for your recommendation!

**Comment by 1forh** [comment]
Added this is the latest version. Will take up to 60 minutes to show in the store.
