### ISSUE TITLE
Can't see the columns in the grid anymore

### ISSUE THREAD

**Issue by loratov** [1forh/bs-grid-chrome-extension#6]
It just shows as one big blue block

**Comment by 1forh** [comment]
This might be a dumb question so apologies but are you sure you're using the `Bootstrap Grid Overlay` extension found here: [link](https://chrome.google.com/webstore/detail/bootstrap-grid-overlay/mnlklmelflkheijccafopdohgclfefcg)?

This overlay is green and doesn't give you the ability to change the color so it's just weird that yours is blue.

**Comment by 1forh** [comment]
Here is a screenshot of it working correctly for me.

<img width="1167" alt="Screenshot 2019-07-04 12 55 52" src="https://user-images.githubusercontent.com/3261185/60680890-1ef38880-9e5b-11e9-8b26-be03f174cec6.png">

**Comment by loratov** [comment]
By blue I mean green :)

I just tested it on the Bootstrap 3 site: https://getbootstrap.com/docs/3.3/ and I get the same problem - so maybe it's specific to B3? 

![AwesomeScreenshot-Bootstrap-The-world-s-most-popular-mobile-first-and-responsive-front-end-framework-2019-07-04-21-07-13](https://user-images.githubusercontent.com/37795755/60683613-5d139b00-9ea1-11e9-969d-606aeba79c14.png)
![AwesomeScreenshot-Bootstrap-The-world-s-most-popular-mobile-first-and-responsive-front-end-framework-2019-07-04-21-07-99](https://user-images.githubusercontent.com/37795755/60683616-5e44c800-9ea1-11e9-99b8-09b36235eaec.png)

**Comment by 1forh** [comment]
@loratov heyo, I published a fix for this issue. definitely was specific to Bootstrap 3 but should be fixed in next release. Should be available in the next hour or two! 

Let me know if you have any other issues! Thanks for the heads up on this one!
